### ISSUE TITLE
What‘s the GPU requirement and how much is the training time?

### ISSUE THREAD

**Issue by BJTUJia** [InnovArul/personreid_sequential_rl#2]
Dear Arulkumar, thanks a lot for this awesome repo. I am quite new to RL and may need your help with the codes. What's the command line that made the project run? I can't seem to find a .sh or .py that does this. Also, how many GPU do I need? I only have two with 12G memory. Thanks a lot for your reply!

**Comment by InnovArul** [comment]
Hi, Thanks for your interest in the repo. 
About the commandline arguments, please look at the files mentioned here: https://github.com/InnovArul/personreid_sequential_rl#stage-1--pre-training and https://github.com/InnovArul/personreid_sequential_rl#stage-2--dqn-training. Most of the params should be the same as the default values given in the file.  You can directly call the respective python files `doall_***.py` to run the training for particular stages.

When I implemented this project, I had only one 1080 Ti GPU at my disposal. So I used only one GPU for my experiments. To me,  stage1 training took 8 to 10 hours,  stage 2 training took around 2.5 days.  Pl. note that the code is not parallelized so much. But it is good enough for small datasets like PRID2011. You may need to spend time in parallelizing if you want to use it for large datasets (MARS, DukeMTMC-VideoReID).

**Comment by BJTUJia** [comment]
Thank you so much for your help!  I will give it a go! Cheers!

**Comment by InnovArul** [comment]
Closing the issue for now. Pl. feel free to reopen if needed.
